### ISSUE TITLE
fromat instead of println and concat

### ISSUE THREAD

**Issue by claudemartin** [code0monkey1/fragmaData#1]
https://github.com/code0monkey1/fragmaData/blob/4c8215a3749fe90cdf7168b160c864690f94347b/src/controller/Statistics.java#L56

This should be: 
```java
int count =  sortedTeams.size() < top ? sortedTeams.size() : top;
System.out.format("Top %d teams in the year %d are :%n", count, year);
```

Note that `%n` will use the system line break instead of just `\n` and it's much easier to read.

**Comment by code0monkey1** [comment]
Done ! _Much cleaner ..._
