### ISSUE TITLE
Why is "type" not an enum?

### ISSUE THREAD

**Issue by claudemartin** [code0monkey1/fragmaData#2]
https://github.com/code0monkey1/fragmaData/blob/4c8215a3749fe90cdf7168b160c864690f94347b/src/model/Ball.java#L36

What kind of _type_ is that and why is it an `int` instead of an `enum`? Then you could use an `EnumMap<Type, Integer>`.

**Comment by code0monkey1** [comment]
I was going to do that Initially , but as I was not sure of it's performance guarantee , I stuck to hashMaps. Now I've learned that EnumMaps are the most efficient among all map implementations , O(1) insert / lookup , as they use an 64 bit bitset , and the assignment and updating is done though Bit Manipulation operations ....  I'll surely change it to an EnumMap now .

**Comment by code0monkey1** [comment]
Done!
